//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarRentalApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class AddRecord
    {
        public string Customer_Name { get; set; }
        public Nullable<decimal> Cost { get; set; }
        public int Customer_Id { get; set; }
        public Nullable<System.DateTime> date_Rented { get; set; }
        public Nullable<System.DateTime> date_Returned { get; set; }
        public Nullable<int> Car_Id { get; set; }
    
        public virtual CarType CarType { get; set; }
    }
}
